### ISSUE TITLE
Tool tip is not needed under Scenarios table

### ISSUE THREAD

**Issue by vikramvi** [hiptest/hiptest-issue-tracker#56] opened 2017-10-18 08:59 UTC
![tool_tip_not_needed](https://user-images.githubusercontent.com/308490/31709784-548dffe2-b3f3-11e7-8d0b-2f0d13df92b4.png)

- Tool tip is not needed here
- also if user does mouse over; sometimes tool tip text is just shown plain / partial blank or broken

**Comment by vikramvi** [comment] 2017-10-19 11:46
@cbliard ping

**Comment by jracenet** [comment] 2017-10-19 11:54
Hi @vikramvi,
We are a bit mixed about this. The links to elements all have a tooltip, in case of the name doesn't fit fully in the zone, so we don't want to remove them.
However, I'm not able to reproduce your issue about broken tool tip text. Could you post a screenshot for this one please? :-)

**Comment by vikramvi** [comment] 2017-10-20 09:15
@jracenet I'm not able to take screen shot; as tool tip gets closed when I try to get screen shot. I'm using latest chrome browser on Ubuntu.

I agree with your point that tool tip is needed in case scenario text is too long.

**Comment by jracenet** [comment] 2017-10-24 15:11
We haven't been able to reproduce the issue and we won't remove the tooltips on the scenarios list item.
I close this one.

**Closed by jracenet** 2017-10-24 15:11 UTC
